defaults: &defaults
  docker:
    - image: circleci/node:8
  working_directory: /tmp/obsessive-trippin

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn

      - run: yarn build

      - persist_to_workspace:
          root: /tmp/obsessive-trippin
          paths:
            - .firebaserc
            - firebase.json
            - firestore.indexes.json
            - firestore.rules
            - package.json
            - src
            - build
            - node_modules

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/obsessive-trippin

      - run: yarn test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/obsessive-trippin

      - run:
          name: Deploy to production
          command: yarn deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
